---
darwin:
  nvram:
    StartupMute: "%01"

  # For more information, see:
  #
  #   - https://macos-defaults.com
  #
  # TODO(ttlgcc): Scan the following references for more properties:
  #   - https://www.defaults-write.com
  #   - https://mths.be/macos
  #   - https://github.com/joeyhoer/starter
  defaults:
    /Library/Preferences/SystemConfiguration/com.apple.smb.server:

      # Values:
      #
      # - 437: Latin (United States)
      # - 737: Windows 95 Greek
      # - 850: Latin 1 (Western European)
      # - 852: Latin 2 (Eastern European)
      # - 861: Icelandic
      # - 866: Cyrillic (Russian)
      # - 932: Japanese Shift-JIS
      # - 936: Simplified Chinese
      # - 949: Korean Hangul
      # - 950: Traditional Chinese
      DOSCodePage: 850
      NetBIOSName: $(hostname)
      ServerDescription: $(hostname)
    /Library/Preferences/com.apple.loginwindow:
      AdminHostInfo: HostName
      DisableConsoleAccess: true
      GuestEnabled: false
    NSGlobalDomain:
      _HIHideMenuBar: true
      AppleActionOnDoubleClick: Maximize
      AppleAquaColorVariant: 1
      AppleEnableMenuBarTransparency: false
      AppleEnableMouseSwipeNavigateWithScrolls: false
      AppleFontSmoothing: 0
      AppleInterfaceStyleSwitchesAutomatically: true
      AppleICUForce24HourTime: true
      AppleKeyboardUIMode: 3
      AppleLanguages:
        - en-US
        - pt-BR
      AppleLocale: en_US@currency=BRL
      AppleMeasurementUnits: Centimeters
      AppleMetricUnits: true
      AppleMiniaturizeOnDoubleClick: true
      ApplePressAndHoldEnabled: false
      AppleReduceDesktopTinting: true
      AppleShowAllExtensions: true
      AppleShowAllFiles: true
      AppleShowScrollBars: WhenScrolling
      AppleSpacesSwitchOnActivate: true
      AppleTemperatureUnit: Celsius
      CGDisableCursorLocationMagnification: false
      InitialKeyRepeat: 10
      KeyRepeat: 2
      NSAppSleepDisabled: false
      NSAutomaticCapitalizationEnabled: false
      NSAutomaticDashSubstitutionEnabled: false
      NSAutomaticPeriodSubstitutionEnabled: false
      NSAutomaticQuoteSubstitutionEnabled: false
      NSAutomaticSpellingCorrectionEnabled: false
      NSAutomaticWindowAnimationsEnabled: false
      NSBrowserColumnAnimationSpeedMultiplier: 0
      NSCloseAlwaysConfirmsChanges: true
      NSDisableAutomaticTermination: true
      NSDocumentSaveNewDocumentsToCloud: false
      NSDocumentRevisionsWindowTransformAnimation: false
      NSNavPanelExpandedStateForSaveMode: true
      NSNavPanelExpandedStateForSaveMode2: true
      NSScrollAnimationEnabled: false
      NSScrollViewRubberbanding: false
      NSSpellCheckerAutomaticallyIdentifiesLanguages: true
      NSQuitAlwaysKeepsWindows: true
      NSTableViewDefaultSizeMode: 2
      NSTextShowsControlCharacters: true
      NSToolbarFullScreenAnimationDuration: 0.0
      NSToolbarTitleViewRolloverDelay: 0.0
      NSUseAnimatedFocusRing: false
      NSWindowResizeTime: 0.001
      PMPrintingExpandedStateForPrint: true
      PMPrintingExpandedStateForPrint2: true
      QLPanelAnimationDuration: 0.0
      WebAutomaticSpellingCorrectionEnabled: false
      com.apple.keyboard.fnState: false
      com.apple.mouse.linear: true
      com.apple.mouse.scaling: 1.0
      com.apple.sound.beep.feedback: false
      com.apple.sound.beep.flash: true
      com.apple.sound.beep.volume: 0.0
      com.apple.springing.delay: 0.0
      com.apple.springing.enabled: true
      com.apple.swipescrolldirection: true
    com.apple.ActivityMonitor:
      IconType: 0 # app's regular icon
      UpdatePeriod: 5
    com.apple.AppleMultitouchTrackpad:
      DragLock: false
      Dragging: false
      TrackpadThreeFingerDrag: false
      FirstClickThreshold: 1
    com.apple.BezelServices:
      dAuto: true
      kDim: true
      kDimTime: 60
    com.apple.BluetoothAudioAgent:
      Apple Bitpool Max (editable): 80
      Apple Bitpool Min (editable): 80
      Apple Initial Bitpool Max (editable): 80
      Apple Initial Bitpool Min (editable): 80
      Negotiated Bitpool: 80
      Negotiated Bitpool Max: 80
      Negotiated Bitpool Min: 80
    com.apple.CrashReporter:
      DialogType: none
    com.apple.HIToolbox:
      AppleFnUsageType: 2 # show emoji & symbols modal
    com.apple.LaunchServices:
      LSQuarantine: false
    com.apple.MobileSMS:
      MMSShowSubject: false
    com.apple.Music:
      userWantsPlaybackNotifications: false
    com.apple.NetworkBrowser:
      BrowseAllInterfaces: true
    com.apple.Safari:
      ShowFullURLInSmartSearchField: false
    com.apple.SoftwareUpdate:
      ScheduleFrequency: 1
    com.apple.Terminal:
      FocusFollowsMouse: false
    com.apple.TextEdit:
      RichText: false
      PlainTextEncoding: 4 # UTF-8
      PlainTextEncodingForWrite: 4 # UTF-8
      SmartQuotes: false
    com.apple.TimeMachine:
      AutoBackup: true
      DoNotOfferNewDisksForBackup: true
    com.apple.appleseed.FeedbackAssistant:
      Autogather: false
    com.apple.desktopservices:
      DSDontWriteNetworkStores: true
      DSDontWriteUSBStores: true
    com.apple.dock:
      autohide: true
      autohide-delay: 0.0
      autohide-time-modifier: 0.5
      dashboard-in-overlay: true
      enable-spring-load-actions-on-all-items: false
      expose-animation-duration: 0.0
      expose-group-apps: true
      expose-group-by-app: true
      launchanim: false
      mineffect: scale
      minimize-to-application: false
      mru-spaces: false
      mcx-disabled: true
      no-bouncing: true
      orientation: bottom
      persistent-apps: []
      scroll-to-open: false
      show-process-indicators: true
      show-recents: false
      showhidden: true
      springboard-hide-duration: 0.0
      springboard-show-duration: 0.0
      springboard-page-duration: 0.0
      static-only: true
      tilesize: 48
      workspaces-auto-swoosh: false

      # TODO(ttlgcc): Hot corners. Values:
      #
      #  0. NOP
      #  2. Mission Control
      #  3. Show application windows
      #  4. Desktop
      #  5. Start screen saver
      #  6. Disable screen saver
      #  7. Dashboard
      # 10. Put display to sleep
      # 11. Launchpad
      # 12. Notification Center
      #
      #wvous-tl-corner: 2
      #wvous-tl-modifier: 0
      #wvous-tr-corner: 2
      #wvous-tr-modifier: 0
      #wvous-bl-corner: 5
      #wvous-bl-modifier: 0
      #wvous-br-corner: 0
      #wvous-br-modifier: 0

    com.apple.finder:
      _FXSortFoldersFirst: true
      _FXSortFoldersFirstOnDesktop: true
      CreateDesktop: true
      DisableAllAnimation: true
      FXDefaultSearchScope: SCcf # current folder
      FXEnableExtensionChangeWarning: false
      FXInfoPanesExpanded.General: true
      FXInfoPanesExpanded.OpenWith: true
      FXInfoPanesExpanded.Privileges: true
      FXPreferredViewStyle: Nlsv # list view
      FXRemoveOldTrashItems: true
      NewWindowTarget: PfHm
      NewWindowTargetPath: file://$HOME/
      QLEnableTextSelection: true
      QuitMenuItem: false
      ShowExternalHardDrivesOnDesktop: true
      ShowHardDrivesOnDesktop: true
      ShowMountedServersOnDesktop: true
      ShowPathbar: true
      ShowRemovableMediaOnDesktop: true
      WarnOnEmptyTrash: false
    com.apple.helpviewer:
      DevMode: true
    com.apple.mail:
      AddressesIncludeNameOnPasteboard: false
      ConversationViewSortDescending: true
      DisableInlineAttachmentViewing: true
      DisableReplyAnimations: true
      DisableSendAnimations: true
      DisableURLLoading: true
      SendFormat: Plain
    com.apple.menuextra.clock:
      DateFormat: EEE d MMM HH:mm
      IsAnalog: false
      ShowDate: true
      ShowDayOfWeek: true
    com.apple.print.PrintingPrefs:
      Quit When Finished: true
    com.apple.screencapture:
      disable-shadow: true
      include-date: true
      location: $HOME/Desktop
      show-thumbnail: true
      type: png
    com.apple.screensaver:
      askForPassword: true
      askForPasswordDelay: 0
      loginWindowIdleTime: 0
    com.apple.spaces:
      spans-displays: false
    com.apple.systemsound:
      com.apple.sound.uiaudio.enabled: false
    com.apple.universalaccess:
      HIDScrollZoomModifierMask: 262144 # TODO(ttlgcc): Explain what this mask means.
      closeViewPressOnReleaseOff: true
      closeViewScrollWheelToggle: true
      closeViewSmoothImages: false
      closeViewZoomFollowsFocus: true
      closeViewZoomMode: 1 # picture-in-picture
      increaseContrast: false
      reduceTransparency: true
      showWindowTitlebarIcons: false
    org.gpgtools.common:
      DisableKeychain: true

  killall:
    - Activity Monitor
    - Dock
    - Finder
    - SystemUIServer
    #- Terminal # NOTE(ttlgcc): chezmoi might be running on a terminal, so don't kill it.
    - TextEdit

