# TODO(ttlgcc): Support arrays.
darwin:
  # https://macos-defaults.com/
  defaults:
    NSGlobalDomain:
      ApplePressAndHoldEnabled: false
    com.apple.TextEdit:
      RichText: false
      SmartQuotes: false
    com.apple.TimeMachine:
      DoNotOfferNewDisksForBackup: true
    com.apple.appleseed.FeedbackAssistance:
      Autogather: false
    com.apple.dock:
      autohide: true
      autohide-delay: 0.2
      autohide-time-modifier: 0.5
      mineffect: scale
      orientation: bottom
      scroll-to-open: false
      show-recents: true
      static-only: false
      tilesize: 48
    com.apple.screencapture:
      disable-shadow: false
      include-date: true
      location: $HOME/Desktop
      show-thumbnail: true
      type: png

  nvram:
    # Disable sound effects on boot.
    SystemAudioVolume: " "

  # TODO(ttlgcc): I don't like the "killall" name -
  #  we're also killing applications before setting defaults.
  #  Come out with a different convention.
  killall:
    - Dock
    - Finder
    - SystemUIServer
    - TextEdit
