---
darwin:
  nvram:
    StartupMute: "%01"

  # NOTE(ttlgcc): For more information, see:
  #
  #   - https://macos-defaults.com
  #
  # TODO(ttlgcc): Scan the following references for more properties:
  #   - https://www.defaults-write.com
  #   - https://mths.be/macos
  #   - https://github.com/joeyhoer/starter
  defaults:
    /Library/Preferences/com.apple.loginwindow:
      AdminHostInfo: HostName
    NSGlobalDomain:
      AppleActionOnDoubleClick: Maximize
      AppleEnableMenuBarTransparency: false
      AppleEnableMouseSwipeNavigateWithScrolls: false
      AppleHighlightColor: "0.212312 0.591682 0.908789"
      AppleInterfaceStyle: Dark
      AppleKeyboardUIMode: 3 # Full keyboard access for all controls.
      AppleLanguages:
        - en-US
        - pt-BR
      AppleLocale: en_US@currency=BRL
      AppleMeasurementUnits: Centimeters
      AppleMetricUnits: true
      AppleMiniaturizeOnDoubleClick: true
      ApplePressAndHoldEnabled: false
      AppleReduceDesktopTinting: true
      AppleShowAllExtensions: true
      AppleShowAllFiles: true
      AppleShowScrollBars: Always
      AppleSpacesSwitchOnActivate: true
      AppleTemperatureUnit: Celsius
      CGDisableCursorLocationMagnification: false
      InitialKeyRepeat: 10
      KeyRepeat: 2
      NSAppSleepDisabled: false
      NSAutomaticCapitalizationEnabled: false
      NSAutomaticDashSubstitutionEnabled: false
      NSAutomaticPeriodSubstitutionEnabled: false
      NSAutomaticQuoteSubstitutionEnabled: false
      NSAutomaticSpellingCorrectionEnabled: false
      NSAutomaticWindowAnimationsEnabled: false
      NSCloseAlwaysConfirmsChanges: true
      NSDisableAutomaticTermination: true
      NSDocumentSaveNewDocumentsToCloud: false
      NSNavPanelExpandedStateForSaveMode: true
      NSNavPanelExpandedStateForSaveMode2: true
      NSScrollAnimationEnabled: true
      NSSpellCheckerAutomaticallyIdentifiesLanguages: true
      NSTableViewDefaultSizeMode: 2
      NSTextShowsControlCharacters: true
      NSToolbarTitleViewRolloverDelay: 0.0
      NSUseAnimatedFocusRing: false
      NSWindowResizeTime: 0.001
      PMPrintingExpandedStateForPrint: true
      PMPrintingExpandedStateForPrint2: true
      WebAutomaticSpellingCorrectionEnabled: false
      com.apple.keyboard.fnState: false
      com.apple.mouse.linear: true
      com.apple.mouse.scaling: 1.0
      com.apple.sound.beep.feedback: false
      com.apple.sound.beep.flash: true
      com.apple.sound.beep.volume: 0.0
      com.apple.springing.enabled: true
      com.apple.springing.delay: 0.0
      com.apple.swipescrolldirection: false
    com.apple.ActivityMonitor:
      IconType: 0 # App's regular icon.
      UpdatePeriod: 5
    com.apple.AppleMultitouchTrackpad:
      DragLock: false
      Dragging: false
      TrackpadThreeFingerDrag: false
      FirstClickThreshold: 1
    com.apple.BezelServices:
      dAuto: true
      kDim: true
      kDimTime: 60
    com.apple.BluetoothAudioAgent:
      Apple Bitpool Min (editable): 40
    com.apple.CrashReporter:
      DialogType: none
    com.apple.HIToolbox:
      AppleFnUsageType: 2 # Show emoji & symbols modal.
    com.apple.LaunchServices:
      LSQuarantine: false
    com.apple.Safari:
      ShowFullURLInSmartSearchField: false
    com.apple.MobileSMS:
      MMSShowSubject: false
    com.apple.Music:
      userWantsPlaybackNotifications: false
    com.apple.Terminal:
      FocusFollowsMouse: false
    com.apple.TextEdit:
      RichText: false
      SmartQuotes: false
    com.apple.TimeMachine:
      AutoBackup: true
      DoNotOfferNewDisksForBackup: true
    com.apple.appleseed.FeedbackAssistant:
      Autogather: false
    com.apple.dock:
      autohide: true
      autohide-delay: 0.0
      autohide-time-modifier: 0.5
      dashboard-in-overlay: true
      enable-spring-load-actions-on-all-items: false
      expose-group-apps: true
      mineffect: scale
      mru-spaces: true
      no-bouncing: true
      orientation: bottom
      scroll-to-open: false
      show-recents: true
      static-only: true
      tilesize: 48
    com.apple.finder:
      _FXSortFoldersFirst: true
      _FXSortFoldersFirstOnDesktop: true
      CreateDesktop: true
      FXDefaultSearchScope: SCcf # Current folder.
      FXEnableExtensionChangeWarning: false
      FXPreferredViewStyle: Nlsv # List view.
      FXRemoveOldTrashItems: true
      QuitMenuItem: false
      ShowExternalHardDrivesOnDesktop: true
      ShowHardDrivesOnDesktop: false
      ShowMountedServersOnDesktop: true
      ShowPathbar: false
      ShowRemovableMediaOnDesktop: true
    com.apple.helpviewer:
      DevMode: true
    com.apple.menuextra.clock:
      DateFormat: '"EEE d MMM HH:mm"'
      FlashDateSeparators: false
    com.apple.print.PrintingPrefs:
      Quit When Finished: true
    com.apple.screencapture:
      disable-shadow: true
      include-date: true
      location: $HOME/Desktop
      show-thumbnail: true
      type: png
    com.apple.spaces:
      spans-displays: false
    com.apple.systempreferences:
      NSQuitAlwaysKeepsWindows: true
    com.apple.systemsound:
      com.apple.sound.uiaudio.enabled: false
    com.apple.universalaccess:
      HIDScrollZoomModifierMask: 262144 # TODO(fmrsn): Explain what this mask means.
      closeViewPressOnReleaseOff: true
      closeViewScrollWheelToggle: true
      closeViewSmoothImages: false
      closeViewZoomFollowsFocus: true
      closeViewZoomMode: 1 # Picture-in-picture.
      increaseContrast: false
      reduceTransparency: true
      showWindowTitlebarIcons: false

  killall:
    - Activity Monitor
    - Dock
    - Finder
    - SystemUIServer
    #- Terminal # NOTE(ttlgcc): chezmoi might be running on a terminal, so don't kill it.
    - TextEdit

