#!/bin/sh
set -eu

# TODO(ttlgcc): Port to Linux.

# Bootstrapping tools:
#
# - age
# - chezmoi
# - rbw

case "$(uname -s)" in
	Darwin)
		export HOMEBREW_NO_ANALYTICS=1
		bash -c "$(curl -fsSL https://github.com/Homebrew/install/raw/HEAD/install.sh)"
		eval "$(/opt/homebrew/bin/brew shellenv)"
		brew analytics off
		brew install --quiet age chezmoi rbw
		;;
	*)
		echo 'OS not supported yet'
		exit 1
		;;
esac

printf 'bitwarden email? '
head -n1 | xargs -- rbw config set email
rbw register
rbw login

chezmoi init --apply tautologicc
chezmoi git config url."git@github.com:".insteadOf "https://github.com/"

yesno 'reboot now' && sudo reboot || :
