#!/bin/sh
set -eu

# TODO(ttlgcc): Port to Linux.

# NOTE(ttlgcc): Install bootstrapping tools:
#
# - age
# - chezmoi
# - rbw
#
case "$(uname -s)" in
	Darwin)
		command -v brew 2>/dev/null || {
			export HOMEBREW_NO_ANALYTICS=1
			bash -c "$(curl -fsSL https://github.com/Homebrew/install/raw/HEAD/install.sh)"
			eval "$(/opt/homebrew/bin/brew shellenv || /usr/local/bin/brew shellenv)"
			brew analytics off
		}
		brew install --quiet age chezmoi rbw
		;;
	*)
		printf 'OS not supported yet\n'
		exit 1
		;;
esac

# NOTE(ttlgcc): Log in to Bitwarden.
#
printf 'bitwarden email? '
head -n1 | xargs rbw config set email
rbw register
rbw login

# NOTE(ttlgcc): Import secrets.
#
for key in .config/age/dotfiles.key .ssh/id_ed25519 .ssh/id_ed25519.pub
do
	mkdir -p ~/$(dirname $key)
	rbw get '~'/$key >~/$key
	chmod 400 ~/$key
done
ssh-add

# NOTE(ttlgcc): Clone configuration files.
#
chezmoi init --apply tautologicc
chezmoi git config url.'git@github.com:'.insteadOf 'https://github.com/'

# NOTE(ttlgcc): Reboot machine.
#
yesno 'reboot now' && sudo reboot || :
