#!/bin/sh

# Install Homebrew
command -v brew >/dev/null || {
	bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >>~/.zprofile
	eval "$(/opt/homebrew/bin/brew shellenv)"
}

defaults write -g ApplePressAndHoldEnabled -bool false
